// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApiTraining.Data.Data;

#nullable disable

namespace WebApiTraining.Data.Migrations
{
    [DbContext(typeof(FstssDataContext))]
    partial class FstssDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApiTraining.Data.Entities.Lot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Lots", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Lot 1",
                            PlatformId = 8
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lot 2",
                            PlatformId = 8
                        },
                        new
                        {
                            Id = 3,
                            Name = "Lot 3",
                            PlatformId = 8
                        });
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.Maintainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Maintainers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Flight Safety"
                        },
                        new
                        {
                            Id = 2,
                            Name = "L3Harris"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AVT"
                        });
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.ManModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LotId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LotId");

                    b.ToTable("ManModule", (string)null);
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaintainerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaintainerId");

                    b.ToTable("Platforms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = false,
                            MaintainerId = 1,
                            Name = "AH-64E"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MaintainerId = 2,
                            Name = "CH-47F"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MaintainerId = 1,
                            Name = "TH-1H"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MaintainerId = 2,
                            Name = "UH-60L"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            MaintainerId = 2,
                            Name = "UH-60M"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            MaintainerId = 1,
                            Name = "UH-72A"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            MaintainerId = 1,
                            Name = "UH-72CPT"
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            MaintainerId = 2,
                            Name = "RCTD"
                        });
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.Simulator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PlatformId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.ToTable("Simulators", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "5932",
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "5933",
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "5934",
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "5935",
                            PlatformId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "7601",
                            PlatformId = 3
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "7602",
                            PlatformId = 3
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "5930",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Name = "5921",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Name = "5924",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Name = "5925",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Name = "5926",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Name = "5927",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Name = "5928",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Name = "5937",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Name = "5938",
                            PlatformId = 4
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Name = "8719",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Name = "8720",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Name = "8721",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 19,
                            IsActive = true,
                            Name = "8722",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 20,
                            IsActive = true,
                            Name = "8723",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 21,
                            IsActive = true,
                            Name = "8724",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 22,
                            IsActive = true,
                            Name = "8725",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 23,
                            IsActive = true,
                            Name = "8726",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 24,
                            IsActive = true,
                            Name = "8727",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 25,
                            IsActive = true,
                            Name = "8728",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 26,
                            IsActive = true,
                            Name = "8729",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 27,
                            IsActive = true,
                            Name = "8730",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 28,
                            IsActive = true,
                            Name = "8731",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 29,
                            IsActive = true,
                            Name = "8732",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 30,
                            IsActive = true,
                            Name = "8733",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 31,
                            IsActive = true,
                            Name = "8734",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 32,
                            IsActive = true,
                            Name = "8735",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 33,
                            IsActive = true,
                            Name = "8736",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 34,
                            IsActive = true,
                            Name = "8737",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 35,
                            IsActive = true,
                            Name = "8738",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 36,
                            IsActive = true,
                            Name = "8739",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 37,
                            IsActive = true,
                            Name = "8740",
                            PlatformId = 5
                        },
                        new
                        {
                            Id = 38,
                            IsActive = true,
                            Name = "8745",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 39,
                            IsActive = true,
                            Name = "8746",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 40,
                            IsActive = true,
                            Name = "8747",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 41,
                            IsActive = true,
                            Name = "8748",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 42,
                            IsActive = true,
                            Name = "8749",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 43,
                            IsActive = true,
                            Name = "8750",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 44,
                            IsActive = true,
                            Name = "8751",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 45,
                            IsActive = true,
                            Name = "8752",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 46,
                            IsActive = true,
                            Name = "8753",
                            PlatformId = 6
                        },
                        new
                        {
                            Id = 47,
                            IsActive = true,
                            Name = "8754",
                            PlatformId = 6
                        });
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.Lot", b =>
                {
                    b.HasOne("WebApiTraining.Data.Entities.Platform", null)
                        .WithMany("Lots")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.ManModule", b =>
                {
                    b.HasOne("WebApiTraining.Data.Entities.Lot", null)
                        .WithMany("ManModules")
                        .HasForeignKey("LotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.Platform", b =>
                {
                    b.HasOne("WebApiTraining.Data.Entities.Maintainer", "Maintainer")
                        .WithMany()
                        .HasForeignKey("MaintainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Maintainer");
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.Simulator", b =>
                {
                    b.HasOne("WebApiTraining.Data.Entities.Platform", "Platform")
                        .WithMany("Simulators")
                        .HasForeignKey("PlatformId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Platform");
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.Lot", b =>
                {
                    b.Navigation("ManModules");
                });

            modelBuilder.Entity("WebApiTraining.Data.Entities.Platform", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("Simulators");
                });
#pragma warning restore 612, 618
        }
    }
}
